services:
  web:
    image: ghcr.io/sostinewaliaula/caava-web:feature-ldap
    restart: always
    env_file:
      - .env
    depends_on:
      - api

  api:
    image: ghcr.io/sostinewaliaula/caava-api:feature-ldap
    restart: always
    command: ./bin/docker-entrypoint-api.sh
    env_file:
      - .env
    environment:
      - REDIS_URL=redis://plane-redis:6379/0
      - DATABASE_URL=postgresql://${POSTGRES_USER}:${POSTGRES_PASSWORD}@plane-db:5432/${POSTGRES_DB}
    depends_on:
      - plane-db
      - plane-redis

  worker:
    image: ghcr.io/sostinewaliaula/caava-api:feature-ldap
    restart: always
    command: ./bin/docker-entrypoint-worker.sh
    env_file:
      - .env
    environment:
      - REDIS_URL=redis://plane-redis:6379/0
      - DATABASE_URL=postgresql://${POSTGRES_USER}:${POSTGRES_PASSWORD}@plane-db:5432/${POSTGRES_DB}
    depends_on:
      - api
      - plane-db
      - plane-redis

  beat-worker:
    image: ghcr.io/sostinewaliaula/caava-api:feature-ldap
    restart: always
    command: ./bin/docker-entrypoint-beat.sh
    env_file:
      - .env
    environment:
      - REDIS_URL=redis://plane-redis:6379/0
      - DATABASE_URL=postgresql://${POSTGRES_USER}:${POSTGRES_PASSWORD}@plane-db:5432/${POSTGRES_DB}
    depends_on:
      - api
      - plane-db
      - plane-redis

  migrator:
    image: ghcr.io/sostinewaliaula/caava-api:feature-ldap
    restart: no
    command: ./bin/docker-entrypoint-migrator.sh
    env_file:
      - .env
    environment:
      - REDIS_URL=redis://plane-redis:6379/0
      - DATABASE_URL=postgresql://${POSTGRES_USER}:${POSTGRES_PASSWORD}@plane-db:5432/${POSTGRES_DB}
    depends_on:
      - plane-db
      - plane-redis

  plane-db:
    image: postgres:15.7-alpine
    restart: always
    command: postgres -c 'max_connections=1000'
    volumes:
      - pgdata_ldap:/var/lib/postgresql/data
    env_file:
      - .env
    environment:
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_DB: ${POSTGRES_DB}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}

  plane-redis:
    image: valkey/valkey:7.2.11-alpine
    restart: always
    volumes:
      - redisdata_ldap:/data

  plane-mq:
    image: rabbitmq:3.13.6-management-alpine
    restart: always
    env_file:
      - .env
    environment:
      - RABBITMQ_DEFAULT_USER=${RABBITMQ_USER}
      - RABBITMQ_DEFAULT_PASS=${RABBITMQ_PASSWORD}
      - RABBITMQ_DEFAULT_VHOST=${RABBITMQ_VHOST}
    volumes:
      - rabbitmq_data_ldap:/var/lib/rabbitmq

  plane-minio:
    image: minio/minio
    restart: always
    command: server /export --console-address ":9090"
    volumes:
      - uploads_ldap:/export
    environment:
      MINIO_ROOT_USER: ${AWS_ACCESS_KEY_ID}
      MINIO_ROOT_PASSWORD: ${AWS_SECRET_ACCESS_KEY}

  proxy:
    image: ghcr.io/sostinewaliaula/caava-proxy:feature-ldap
    restart: always
    ports:
      - ${LISTEN_HTTP_PORT:-8092}:80
    env_file:
      - .env
    depends_on:
      - web
      - api

volumes:
  pgdata_ldap:
  redisdata_ldap:
  uploads_ldap:
  rabbitmq_data_ldap:
